### ISSUE TITLE
What about provide dump to and restore from array?

### ISSUE THREAD

**Issue by jiabinruan** [hideo55/cpp-HyperLogLog#10]
void dump(std::string& data) {
    	data.clear();
    	data.append((char*)&b_, sizeof(b_));
    	data.append((char*)&M_[0], sizeof(M_[0]) * M_.size());
    }

    void restore(const std::string& data) {
        std::string::const_iterator it = data.begin();
        uint8_t b = (uint8_t)*it;
        HyperLogLog tempHLL(b);
        tempHLL.M_.clear();
        tempHLL.M_.assign(it + 1, it + tempHLL.m_);
        swap(tempHLL);
    }

**Comment by hideo55** [comment]
Why don't you use stringstream?

**Comment by jiabinruan** [comment]
oh, that is a way.
