### ISSUE TITLE
Comment technical limitation of buckets

### ISSUE THREAD

**Issue by Alexxz** [hideo55/cpp-HyperLogLog#6]
Hi @hideo55 , thank you for this project. It works perfect.
I need your comment why you limited maximim number of buckets to 2^16. 
Is it something technical that I have not noticed in code?
Or it is something like anti-idiots protection?
I want to perform simulations on 2^18 buckets  and I'm not sure if I can just raise the constant value. 
 I need to make sure HLL gives error less than 0.1%

**Comment by hideo55** [comment]
The limitation is derived from fig.3 of http://algo.inria.fr/flajolet/Publications/FlFuGaMe07.pdf . But, it is not absolute(it is common "practical" value).

I did extend maximum number of buckets up to 2^30(#7).

**Comment by Alexxz** [comment]
Thank you very much!
